@startuml

class Default {
    Integer id
    Timestamp createdAt
    Timestamp updatedAt
}

class User {
    String email
    String pass

    + registUser()
    + login()
    + list()
}

class Task {
    String name
    String description
    Date limit
    Integer didIt

    + search()
    + registTask()
    + didTask()
    + update()
}

class Category {
    String name
    Integer userId

    + initialCategory()
    + search()
    + registCategory()
}

Default <|-- User
Default <|-- Task
Default <|-- Category

User "1"-"*" Task
Task "*"-"1" Category


@enduml
